#!/bin/bash

quotes=(
"Believe you can and you're halfway there."
"Success is not final, failure is not fatal."
"Don't watch the clock, do what it does."
"Keep your eyes on the stars, and your feet on the ground."
"You miss 100% of the shots you don't take."
"I have not failed, I've just found 10,000 ways that won't work."
"You are never too old to set another goal."
"The only way to do great work is to love what you do."
"Keep going, things will get better."
"Don't let yesterday take up too much of today."
"You don't have to be great to start, but you have to start to be great."
"Do something today that your future self will thank you for."
"The greatest glory in living lies not in never falling, but in rising every time we fall."
"Your time is limited, so don't waste it living someone else's life."
"You are stronger than you seem, braver than you believe, and smarter than you think."
"It always seems impossible until it's done."
"The best way to predict your future is to create it."
"Don't let fear hold you back, let it push you forward."
"You can't go back and change the beginning, but you can start where you are and change the ending."
"The only limit to our realization of tomorrow will be our doubts of today."
"You don't have to control your thoughts, you just have to stop letting them control you."
"Success is not about being better than someone else, it's about being better than you were yesterday."
"Do what you can, with what you have, where you are."
"You are one decision away from a completely different life."
"The future belongs to those who believe in the beauty of their dreams."
"You can't start the next chapter of your life if you keep re-reading the last one."
"Life is 10% what happens to you and 90% how you react to it."
"You are never too young to make a difference."
"The best revenge is massive success."
"Don't let the fear of losing be greater than the excitement of winning."
"You don't get what you wish for, you get what you work for."
"The only person you should try to be better than is the person you were yesterday."
"It's not about being the best, it's about being better than you were yesterday."
"You can't hit a target you can't see."
"I don't count my sit-ups, I only start counting when it starts burning."
"You are not a product of your circumstances, you are a product of your decisions."
"The greatest risk is the risk of not taking the risk."
"You can waste your lives drawing lines, or you can live your life crossing them."
"The best way to get started is to quit talking and begin doing."
"You don't learn to walk by following rules, you learn by doing."
"Experience is the teacher of all things."
"You can't build joy on a foundation of shame."
"The biggest adventure you can take is to live the life of your dreams."
"You are the architect of your own destiny."
"Don't be afraid to give up the good to go for the great."
"The best is yet to come."
"You can't reach for anything new if your hands are still full of yesterday's junk."
"Life begins at the end of your comfort zone."
"You don't have to be perfect to be amazing."
"The biggest risk is not taking any risk."
)
random_quote=$(( RANDOM % ${#quotes[@]} ))
echo "Here is a quote for your day: ${quotes[$random_quote]}"
